name: test_vulnerabilities
on: 
 push:
   branches:
     - main
jobs:

  openjdk-vulnerabilities:
    env:
      image-name:  test-jdk
      output-file: open_jdk_vulnerabilities
    runs-on: gh-private-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Open JDK container image
        run: | 
          cd ./Java/
          docker build -t ${{ env.image-name }} .
      - name: Run the container
        run: docker run ${{ env.image-name }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.image-name }}
          format: 'table'
          output: '${{ env.output-file }}'
          severity: 'CRITICAL,HIGH'
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file }}
        
  wolfi-jre-vulnerabilites:
    env:
      image-name: test-wolfi:1.0
      output-file: wolfi-jre-vulnerabilities
    runs-on: gh-private-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Build Wolfi JRE image
        run: |
          cd ./Wolfi-JRE/
          docker build -t  ${{ env.image-name }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.image-name }}
          format: 'table'
          output: '${{ env.output-file }}'
          severity: 'CRITICAL,HIGH'
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file}}
          
      
    # Comment for triggering Workflow.
