name: test_vulnerabilities
on: 
 push:
   branches:
     - main
jobs:

  openjdk-vulnerabilities:
    env:
      image-name:  test-jdk
      output-file: open_jdk_vulnerabilities
      DOCKER_HOST: tcp://localhost:2375
    runs-on: gh-private-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Wait for Docker Daemon to start
        run: |
          echo "Waiting for Docker daemon to initialize on port 2375..."
          timeout 30s bash -c 'until printf "" 2>/dev/null >/dev/tcp/127.0.0.1/2375; do sleep 10; done'
          echo "Docker daemon is up and responding!"
      - name: Build Open JDK container image
        run: | 
          cd ./Java/
          docker build -t ${{ env.image-name }} .
      - name: Run the container
        run: docker run ${{ env.image-name }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.image-name }}
          format: 'table'
          output: '${{ env.output-file }}'
          severity: 'CRITICAL,HIGH'
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file }}
        
  wolfi-jre-vulnerabilites:
    env:
      image-name: test-wolfi:1.0
      output-file: wolfi-jre-vulnerabilities
      DOCKER_HOST: tcp://localhost:2375
    runs-on: gh-private-runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Wait for Docker Daemon to start
        run: |
          echo "Waiting for Docker daemon to initialize on port 2375..."
          timeout 30s bash -c 'until printf "" 2>/dev/null >/dev/tcp/127.0.0.1/2375; do sleep 10; done'
          echo "Docker daemon is up and responding!"
      - name: Build Wolfi JRE image
        run: |
          cd ./Wolfi-JRE/
          docker build -t  ${{ env.image-name }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.image-name }}
          format: 'table'
          output: '${{ env.output-file }}'
          severity: 'CRITICAL,HIGH'
      - name: Output Vulnerabilities
        run: cat ${{ env.output-file}}
          
      
    # Comment for triggering Workflow..
